// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// crunBMLGrid
IntegerMatrix crunBMLGrid(IntegerMatrix g, int numSteps);
RcppExport SEXP BMLGrid_crunBMLGrid(SEXP gSEXP, SEXP numStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type numSteps(numStepsSEXP);
    __result = Rcpp::wrap(crunBMLGrid(g, numSteps));
    return __result;
END_RCPP
}
